name: Generate Tokens

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 1"

jobs:
    generate-tokens:
        runs-on: ubuntu-latest

        permissions:
            contents: write
            pull-requests: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 8

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "pnpm"
                  cache-dependency-path: "fondue/pnpm-lock.yaml"

            - name: Install dependencies
              working-directory: ./fondue
              run: pnpm install --frozen-lockfile

            - name: Build tokens
              working-directory: ./fondue
              env:
                  FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
              run: pnpm build:tokens

            - name: Check for changes
              id: git_diff
              run: |
                  if git diff --quiet; then
                    echo "No changes detected after building tokens."
                    echo "changed=false" >> $GITHUB_OUTPUT
                  else
                    echo "Changes detected after building tokens."
                    echo "changed=true" >> $GITHUB_OUTPUT
                  fi

            - name: Create changeset
              if: steps.git_diff.outputs.changed == 'true'
              working-directory: ./fondue
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  mkdir -p .changeset
                  echo -e "---\n'@frontify/fondue-tokens': patch\n---\n\nUpdated Tokens from Figma" > .changeset/automated-tokens.md
                  git add .changeset/automated-tokens.md

            - name: Create Pull Request
              if: steps.git_diff.outputs.changed == 'true'
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: "chore(tokens): update design tokens"
                  title: "chore(tokens): Update design tokens"
                  body: |
                      This PR updates the design tokens based on the latest changes.

                      This is an automated PR.
                  branch: chore/tokens/update-generated-tokens
                  labels: automated pr, fondue
                  signoff: true
