name: Update Icons

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 1" # Run every Monday at midnight UTC

jobs:
    update-icons:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Use pnpm
              uses: pnpm/action-setup@v3

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm i --frozen-lockfile

            - name: Build Fondue Tokens
              run: pnpm build:tokens

            - name: Build icons
              run: pnpm build:icons
              env:
                  FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}

            - name: Generate icons
              run: pnpm --stream --filter {packages/fondue} generate:icons

            - name: Check for changes
              id: git-check
              run: |
                  git add .
                  git diff --staged --quiet || echo "changes=true" >> $GITHUB_OUTPUT

            - name: Create Unique Changeset
              if: steps.git-check.outputs.changes == 'true'
              id: create-changeset
              run: |
                  TIMESTAMP=$(date +%Y%m%d%H%M%S)
                  CHANGESET_FILE=".changeset/update-icons-${TIMESTAMP}.md"
                  echo "---
                  '@frontify/fondue-icons': minor
                  ---

                  feat: update icons" > "$CHANGESET_FILE"

            - name: Create Pull Request
              if: steps.git-check.outputs.changes == 'true'
              uses: peter-evans/create-pull-request@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: "feat: update icons"
                  title: "feat: update icons"
                  body: |
                      This PR updates the icons using the latest changes.

                      Auto-generated by GitHub Actions.
                  branch: update-icons
                  base: main
                  team-reviewers: frontify/frontend-platform

            - name: No changes
              if: steps.git-check.outputs.changes != 'true'
              run: echo "No changes to commit. Skipping PR creation."
